### ISSUE TITLE
Incorrect cleaning of the name of the keys on Windows

### ISSUE THREAD

**Issue by TiiRiiX** [Dysman/bgTools-playerPrefsEditor#12]
Hi, thanks for your asset, it helps out very often. Yesterday I found a bug that not all keys are shown in the editor. After studying the sources, I found the problem and was able to fix it.

It appears on Windows in this place:
`BgTools.PlayerPrefsEditor.WindowsPrefStorage.FetchKeysFromSystem`

![image](https://user-images.githubusercontent.com/10673591/164878801-1f976640-b42d-4b59-b59f-340fcfff8ca3.png)

He successfully receives the keys. But then he cleans the names.
`cachedData = cachedData.Select((key) => { return key.Substring(0, key.IndexOf("_h")); }).ToArray();`

And as you may have noticed in the screenshot, part of the key also falls under this cleaning. From which, in the subsequent code, an incorrect key is processed, which as a result is not displayed in the editor.

Locally I corrected like this:
`cachedData = cachedData.Select((key) => { return key.Substring(0, key.LastIndexOf("_h")); }).ToArray();`

![image](https://user-images.githubusercontent.com/10673591/164878926-7d252076-6e58-426a-8333-9333f2a3b688.png)

And it works!

**Comment by Dysman** [comment]
Issue validated

Keys that uses '_' as seperator and the followed part starts with an 'h' ends into wrong detected key's. And this wrong key's will be not listed in the UI.
