### ISSUE TITLE
Version mismatched

### ISSUE THREAD

**Issue by favoyang** [Dysman/bgTools-playerPrefsEditor#2]
Issue
- GitHub Release v1.0.1
- package.json 1.0.0

Fix: bump package.json to 1.0.1 then retag v1.0.1

And, you may want to check out [this post](https://medium.com/openupm/how-to-maintain-upm-package-part-4-managing-package-release-with-cli-972ff5311163) for managing the release process with CLI.

**Comment by Dysman** [comment]
Thanks for reporting and the link. Will fix it directly.
