### ISSUE TITLE
Issue when project has "/" in name, on Mac editor

### ISSUE THREAD

**Issue by simplesab** [Dysman/bgTools-playerPrefsEditor#4]
Hello all,

Encountered an edge case on my Mac editor:
When the project has a "/" in the name, something like "Next A/R", the var `pathToPrefs` in `PreferencesEditorWindow.cs` becomes "Library/Preferences/unity.<comp.name>.Next A/R.plist" but the actual file on disk is located at "Library/Preferences/unity.<comp.name>.Next A_R.plist". Unity avoids the character by replacing it with "_".

I got around this issue locally by modifying line 73 of `PreferencesEditorWindow.cs` to read 
`pathToPrefs = @"Library/Preferences/unity." + PlayerSettings.companyName + "." + PlayerSettings.productName.Replace('/', '_') + ".plist";`

I did not check the naming convention on other platforms, but this seems to fix it for Mac OS.

**Comment by Dysman** [comment]
Issue validated and can be reproduced.

Thanks for the report.

**Comment by Dysman** [comment]
Have added more handling for additional special chars and improved stability for plutil call to read the PlayerPrefs.

**Tested fixes**
- [X] Windows
- [X] Linux
- [X] Mac
