### ISSUE TITLE
License not compatible with Unity asset store

### ISSUE THREAD

**Issue by NaejDoree** [Dysman/bgTools-playerPrefsEditor#5]
Hey I just checked your license file and it is not compliant with the submission rules of the unity asset store, and is effectively annoying for commercial games (and even other free games that might want to use MIT licensing wich was my case)

Here are the rules for reference, the interesing part in our case is the licensing part obviously
https://unity3d.com/fr/asset-store/sell-assets/submission-guidelines

On a little side note, I guess Unity didn't notice since the license file seems to not be included in the unity package, but your license clashes with the default license of the unity asset store so redistributing it like that actually breaks your license too :/ (and also distributing the software without the license file also breaks your license)

I suggest switching out for an MIT licensing or seeking out for an other free license compatible with unity's policy

**Comment by Dysman** [comment]
Thanks for consideration of this issue. I will clarify this situation so soon as possible.
The license topic is all the time not trivial.

**Comment by Dysman** [comment]
I have requested the unity store team related to the license topic and i get response now.

Cite: "... nothing in our Asset Store Provider Agreement stops a publisher from distributing their asset outside of the Asset Store on whatever terms they choose to use."

So double licensing like this plugin here is completely fine. If you get the Plugins from github (manual, git-url-upm, OpenUPM) here, the usage is licensed under GPL-3.0. If you get it from the Unity Asset Store you get it under Unity Asset Store EULA.

The §1.1.1.b in the Unity submission guidelines what lists this MIT license possibility has some different concept. The idea is that you can add a additional license file to the unity package onside of there license. In this special case it's of cause required to have a real open source license with no commercial restrictions to not get in conflict with the store license.
